# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UmeMap
                                 A QGIS plugin
 UmeMap layer managment is a plugin which helps with styles for vector layers that come from a UmeMap server and form management
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-10
        copyright            : (C) 2022 by UmeMap
        email                : marcus.lindh@umea.se
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UmeMap class from file UmeMap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .UmeMap import UmeMap

    return UmeMap(iface)
