# -*- coding: utf-8 -*-
"""
Style Service - Handles saving and loading styles from UmeMap server.
"""

import os
import tempfile
import time
from typing import Callable, Dict, List, Optional, Set, Tuple

from qgis.core import Qgis, QgsApplication, QgsDataProvider, QgsDataSourceUri, QgsMapLayer, QgsProject, QgsTask, QgsVectorLayer
from qgis.PyQt.QtXml import QDomDocument

from ...core.api_client import UmeMapApiClient, ApiResponse, parse_style_document
from ...core.auth_manager import AuthManager
from ...core.wfs_utils import parse_wfs_data_source
from ...ui.utils import log


def _style_category(name: str):
    """Resolve a QgsMapLayer style category across QGIS/PyQt enum styles."""
    scoped = getattr(QgsMapLayer, "StyleCategory", None)
    if scoped is not None and hasattr(scoped, name):
        return getattr(scoped, name)
    return getattr(QgsMapLayer, name)


# Style categories that are generated by the server from the database (value maps,
# aliases, defaults, constraints, editable flags, form init code, attribute table
# columns). Refreshed on layers with a user/project style so the symbology the user
# has set is kept.
ATTRIBUTE_STYLE_CATEGORIES = (
    _style_category("Fields")
    | _style_category("Forms")
    | _style_category("AttributeTable")
)

# Custom property set on layers confirmed to come from a UmeMap server. It is saved
# in the project file, so the layer is still recognised when the server can't be reached.
UMEMAP_LAYER_PROPERTY = "umemap_layer"

# How long an unreachable server is remembered before it is asked again
UNREACHABLE_RETRY_SECONDS = 30


def log_kept_settings(layer: QgsMapLayer, reason: str) -> None:
    """Log that a layer keeps its last known settings because the server style could not be used."""
    log(f"Could not fetch style for '{layer.name()}' ({reason}). "
        f"Keeping the last known settings from the project.", Qgis.Warning)


def server_field_names(style_doc) -> Set[str]:
    """Names of the fields configured in a style's fieldConfiguration."""
    names: Set[str] = set()
    config = style_doc.documentElement().firstChildElement("fieldConfiguration")
    field = config.firstChildElement("field")
    while not field.isNull():
        name = field.attribute("name")
        if name:
            names.add(name)
        field = field.nextSiblingElement("field")
    return names


class StyleService:
    """Service for managing layer styles with UmeMap server."""

    def __init__(self, tr_func: Optional[Callable[[str], str]] = None):
        """
        Initialize StyleService.

        :param tr_func: Translation function for i18n support
        """
        self._tr = tr_func or (lambda x: x)
        # Cache of ServerInfo lookups per WFS url, avoids one request per layer on project load
        self._umemap_server_cache: Dict[str, bool] = {}
        # Servers that could not be reached: url -> (retry after timestamp, reason)
        self._unreachable_servers: Dict[str, Tuple[float, str]] = {}

    def save_to_server(self, layer: QgsMapLayer) -> ApiResponse:
        """
        Save layer's current style to UmeMap server.

        :param layer: QGIS layer to save style from
        :return: ApiResponse with result
        """
        wfs_url, layer_name = parse_wfs_data_source(layer)

        if not wfs_url or not layer_name:
            return ApiResponse(
                status="error",
                data=None,
                message=self._tr("Could not parse WFS data source"),
                code="PARSE_ERROR"
            )

        # Check if server is UmeMap
        if not self._is_umemap_server(wfs_url):
            return ApiResponse(
                status="error",
                data=None,
                message=self._tr("Server is not a UmeMap server"),
                code="NOT_UMEMAP"
            )

        # Save style to temp file
        temp_folder = tempfile.gettempdir()
        qml_path = os.path.join(temp_folder, f"{layer_name}.qml")

        layer.saveNamedStyle(qml_path)

        # Read QML file
        try:
            with open(qml_path, mode="rb") as xml_file:
                xml_data = xml_file.read()
        except Exception as e:
            return ApiResponse(
                status="error",
                data=None,
                message=f"Could not read style file: {str(e)}",
                code="FILE_ERROR"
            )

        # Get auth headers and send to server
        headers = AuthManager.get_headers_from_layer(layer)
        client = UmeMapApiClient(wfs_url, headers)

        return client.save_vector_style(layer_name, xml_data)

    def load_from_server(self, layer: QgsMapLayer, categories=None) -> bool:
        """
        Load and apply style from UmeMap server to layer.

        If the style can't be fetched the layer keeps its current settings
        (e.g. the value maps saved in the project file) and the reason is logged.

        :param layer: QGIS layer to apply style to
        :param categories: Style categories to import, None for the complete style
        :return: True if style was applied, False otherwise
        """
        style_doc = self._fetch_style(layer)
        if not style_doc:
            return False

        if categories is None:
            return self.apply_style_to_layer(layer, style_doc)

        return self.apply_attribute_config_to_layer(layer, style_doc, categories)

    def _fetch_style(self, layer: QgsMapLayer) -> Optional[QDomDocument]:
        """
        Fetch the layer's style from the UmeMap server, logging why if it fails.

        :param layer: UmeMap layer
        :return: The style document, or None if it could not be fetched
        """
        wfs_url, layer_name = parse_wfs_data_source(layer)

        if not wfs_url or not layer_name:
            log(f"Could not parse WFS data source for '{layer.name()}' (url={wfs_url}, typename={layer_name}).", Qgis.Warning)
            return None

        # Check if server is UmeMap
        if not self.is_umemap_layer(layer):
            log(f"Server '{wfs_url}' is not a UmeMap server.", Qgis.Warning)
            return None

        unreachable_reason = self.unreachable_reason(wfs_url)
        if unreachable_reason:
            log_kept_settings(layer, f"server unreachable: {unreachable_reason}")
            return None

        # Get auth headers and fetch style
        headers = AuthManager.get_headers_from_layer(layer)
        client = UmeMapApiClient(wfs_url, headers)

        content, error = client.fetch_vector_style(layer_name)
        if content is None:
            log_kept_settings(layer, f"GetVectorStyle failed: {error}")
            return None

        style_doc, error = parse_style_document(content)
        if not style_doc:
            log_kept_settings(layer, f"invalid style from GetVectorStyle: {error}")
            return None

        return style_doc

    def apply_style_to_layer(self, layer: QgsMapLayer, style_doc) -> bool:
        """
        Apply a style document to a layer.

        :param layer: QGIS layer to apply style to
        :param style_doc: QDomDocument with style
        :return: True if successful, False otherwise
        """
        import_result = layer.importNamedStyle(style_doc)

        if import_result[0]:
            layer.setCustomProperty("umemap_style_applied", True)
            layer.triggerRepaint()
            log(f"UmeMap style applied on '{layer.name()}'.", Qgis.Info)
            return True
        else:
            log(f"Could not import style to '{layer.name()}'.", Qgis.Warning)
            return False

    def apply_attribute_config_to_layer(self, layer: QgsMapLayer, style_doc, categories=ATTRIBUTE_STYLE_CATEGORIES) -> bool:
        """
        Apply only the attribute related parts of a style document to a layer
        (value maps, aliases, defaults, constraints, editable flags, form and
        attribute table configuration),
        keeping the layer's own symbology, labels etc.

        :param layer: QGIS layer to update
        :param style_doc: QDomDocument with style from the server
        :param categories: Style categories to import
        :return: True if successful, False otherwise
        """
        # The Fields category also replaces virtual (expression) fields. Those are
        # created by the user in QGIS and never exist in the server style, so keep them.
        self._copy_expression_fields(layer, style_doc)

        import_result = layer.importNamedStyle(style_doc, categories)

        if import_result[0]:
            log(f"UmeMap attribute settings updated on '{layer.name()}'.", Qgis.Info)
            return True
        else:
            log(f"Could not update attribute settings on '{layer.name()}': {import_result[1]}", Qgis.Warning)
            return False

    def _copy_expression_fields(self, layer: QgsMapLayer, style_doc) -> None:
        """
        Replace the expressionfields element in style_doc with the layer's current one.

        :param layer: Layer whose virtual fields should be preserved
        :param style_doc: QDomDocument that will be imported to the layer
        """
        current_doc = QDomDocument("qgis")
        layer.exportNamedStyle(current_doc, categories=_style_category("Fields"))

        target_root = style_doc.documentElement()
        existing = target_root.firstChildElement("expressionfields")
        if not existing.isNull():
            target_root.removeChild(existing)

        current = current_doc.documentElement().firstChildElement("expressionfields")
        if not current.isNull():
            target_root.appendChild(style_doc.importNode(current, True))

    def _is_umemap_server(self, wfs_url: str) -> bool:
        """
        Check (with cache) if a WFS url belongs to a UmeMap server.

        :param wfs_url: Base URL of the WFS server
        :return: True if server is UmeMap
        """
        return self.server_status(wfs_url) is True

    def server_status(self, wfs_url: str) -> Optional[bool]:
        """
        Check (with cache) if a WFS url belongs to a UmeMap server.

        Definite answers are cached for the session. A server that can't be
        reached is only remembered for a short while, so it is asked again
        once it is back.

        :param wfs_url: Base URL of the WFS server
        :return: True/False if known, None if the server can't be reached
        """
        key = wfs_url.rstrip('/').lower()
        if key in self._umemap_server_cache:
            return self._umemap_server_cache[key]

        if self.unreachable_reason(wfs_url):
            return None

        status, reason = UmeMapApiClient.check_umemap_server(wfs_url)
        self.record_server_status(wfs_url, status, reason)
        return status

    def cached_server_status(self, wfs_url: str) -> Optional[bool]:
        """Cached answer for a WFS url without asking the server, None if not known."""
        return self._umemap_server_cache.get(wfs_url.rstrip('/').lower())

    def record_server_status(self, wfs_url: str, status: Optional[bool], reason: str = "") -> None:
        """
        Remember the result of a ServerInfo lookup.

        :param wfs_url: Base URL of the WFS server
        :param status: True/False if the server answered, None if it could not be reached
        :param reason: Why the server could not be reached
        """
        key = wfs_url.rstrip('/').lower()
        if status is None:
            if key not in self._unreachable_servers:
                log(f"UmeMap server '{wfs_url}' could not be reached ({reason}).", Qgis.Warning)
            self._unreachable_servers[key] = (time.time() + UNREACHABLE_RETRY_SECONDS, reason)
            return

        if self._unreachable_servers.pop(key, None):
            log(f"UmeMap server '{wfs_url}' is reachable again.", Qgis.Info)
        self._umemap_server_cache[key] = status

    def unreachable_reason(self, wfs_url: str) -> str:
        """Reason the server recently could not be reached, empty if it is not known to be down."""
        unreachable = self._unreachable_servers.get(wfs_url.rstrip('/').lower())
        if unreachable and unreachable[0] > time.time():
            return unreachable[1]
        return ""

    def is_umemap_layer(self, layer: QgsMapLayer) -> bool:
        """
        Check if a layer is a UmeMap WFS layer that the plugin should manage.

        :param layer: QGIS layer to check
        :return: True if layer comes from a UmeMap server
        """
        if not layer:
            return False

        wfs_url, layer_name = parse_wfs_data_source(layer)
        if not wfs_url or not layer_name:
            return False

        # Skip CodeList lookup layers (auto-loaded for ValueRelation)
        if layer_name.startswith("CodeList_"):
            return False

        status = self.server_status(wfs_url)
        if status is None:
            # Server can't be reached, trust what the project file says about the layer
            return bool(layer.customProperty(UMEMAP_LAYER_PROPERTY, False))

        if status:
            layer.setCustomProperty(UMEMAP_LAYER_PROPERTY, True)
        return status

    def has_local_style(self, layer: QgsMapLayer) -> bool:
        """
        Check if the layer already has a style that must be kept, i.e. the
        layer comes from a project file or the UmeMap style has been applied before.

        :param layer: QGIS layer to check
        :return: True if the layer's symbology should be kept
        """
        if layer.customProperty("umemap_style_applied", False):
            return True

        style_uri = layer.styleURI()
        return bool(style_uri and style_uri.startswith("project:"))

    def umemap_layers(self) -> List[QgsVectorLayer]:
        """
        Get all UmeMap layers in the current project (CodeList lookup layers excluded).

        :return: List of UmeMap vector layers
        """
        return [
            layer for layer in QgsProject.instance().mapLayers().values()
            if isinstance(layer, QgsVectorLayer) and self.is_umemap_layer(layer)
        ]

    def update_style(self, layer: QgsMapLayer) -> bool:
        """
        Replace the layer's complete style with the style from the UmeMap server,
        then auto-load any CodeList lookup layers the new style needs.

        :param layer: The layer to update
        :return: True if the style was applied
        """
        if not self.load_from_server(layer):
            return False

        self._ensure_codelist_layers(layer)
        return True

    def update_attribute_settings(self, layer: QgsVectorLayer) -> bool:
        """
        Update the layer's attribute settings (value maps, aliases, constraints,
        form and attribute table) from the UmeMap server, keeping its symbology.
        Fields added on the server since the layer was loaded are loaded too,
        then any CodeList lookup layers the new settings need are auto-loaded.

        :param layer: The layer to update
        :return: True if the settings were applied
        """
        style_doc = self._fetch_style(layer)
        if not style_doc:
            return False

        self._load_new_fields(layer, style_doc)

        if not self.apply_attribute_config_to_layer(layer, style_doc):
            return False

        self._ensure_codelist_layers(layer)
        return True

    def _load_new_fields(self, layer: QgsVectorLayer, style_doc) -> None:
        """
        Reload the layer's fields from the server if the style configures fields
        the layer doesn't have yet (attributes added in WebAdmin).
        Skipped when the layer has unsaved edits, since they would be lost.

        :param layer: Layer to update
        :param style_doc: Style from the server
        """
        missing = server_field_names(style_doc) - set(layer.fields().names())
        if not missing:
            return

        if layer.isModified():
            log(f"New fields {sorted(missing)} on '{layer.name()}' were not loaded because the layer "
                f"has unsaved edits. Save or discard them and update again.", Qgis.Warning)
            return

        was_editing = layer.isEditable()
        if was_editing:
            layer.rollBack()  # No unsaved edits, only ends the edit session

        layer.setDataSource(layer.source(), layer.name(), layer.providerType(),
                            QgsDataProvider.ProviderOptions())

        if was_editing:
            layer.startEditing()

        still_missing = server_field_names(style_doc) - set(layer.fields().names())
        if still_missing:
            log(f"Fields {sorted(still_missing)} are configured on the server for '{layer.name()}' "
                f"but are not published by the WFS.", Qgis.Warning)
        else:
            log(f"New fields {sorted(missing)} loaded on '{layer.name()}'.", Qgis.Info)

    def on_layer_added(self, layer: QgsMapLayer) -> None:
        """
        Event handler for when a layer is added to the project.

        New layers get the complete UmeMap style. Layers that already have a
        style (from a project file) keep it, but their attribute settings
        (value maps, aliases, constraints, form, attribute table) are refreshed from the server
        so changes made on the server are picked up. Afterwards any CodeList
        lookup layers required by ValueRelation widgets are auto-loaded.

        :param layer: The layer that was added
        """
        try:
            if not self.is_umemap_layer(layer):
                return

            if self.has_local_style(layer):
                log(f"Local style used for '{layer.name()}', updating attribute settings only.", Qgis.Info)
                success = self.load_from_server(layer, ATTRIBUTE_STYLE_CATEGORIES)
            else:
                success = self.load_from_server(layer)

            if success:
                self._ensure_codelist_layers(layer)
            else:
                log(f"Style could not be applied to '{layer.name()}'.", Qgis.Warning)
        except Exception as e:
            log(f"[ERROR] on_layer_added failed for '{layer.name()}': {e}", Qgis.Critical)

    def _ensure_codelist_layers(self, layer: QgsMapLayer) -> None:
        """
        Check if the layer's style contains ValueRelation widgets that reference
        CodeList WFS layers and auto-load any missing ones.

        :param layer: The layer whose style may reference CodeList layers
        """
        needed_layers = self._find_codelist_layer_refs(layer)
        if not needed_layers:
            return

        # Check which CodeList layers are already loaded
        project = QgsProject.instance()
        loaded_names = {l.name() for l in project.mapLayers().values()}

        wfs_url, _ = parse_wfs_data_source(layer)
        if not wfs_url:
            return

        ds = QgsDataSourceUri(layer.dataProvider().dataSourceUri())
        authcfg = ds.authConfigId() or ""

        for codelist_layer_name in needed_layers:
            if codelist_layer_name in loaded_names:
                log(f"CodeList layer '{codelist_layer_name}' already loaded.", Qgis.Info)
                continue

            self._load_codelist_layer(wfs_url, codelist_layer_name, authcfg)

    def _find_codelist_layer_refs(self, layer: QgsMapLayer) -> Set[str]:
        """
        Parse the layer's style to find ValueRelation widgets referencing CodeList layers.

        :param layer: Layer to inspect
        :return: Set of CodeList layer names referenced by ValueRelation widgets
        """
        codelist_refs: Set[str] = set()

        try:
            # Export current style to QDomDocument
            style_doc = QDomDocument("qgis")
            layer.exportNamedStyle(style_doc)

            # Find all editWidget elements with type="ValueRelation".
            # UmeMapCodeListSearch widgets are intentionally skipped here -
            # they query the server directly and don't need WFS lookup layers.
            edit_widgets = style_doc.elementsByTagName("editWidget")
            for i in range(edit_widgets.count()):
                widget = edit_widgets.at(i).toElement()
                if widget.attribute("type") != "ValueRelation":
                    continue

                # Find the LayerName option within this widget's config
                options = widget.elementsByTagName("Option")
                for j in range(options.count()):
                    opt = options.at(j).toElement()
                    if opt.attribute("name") == "LayerName":
                        layer_name = opt.attribute("value")
                        if layer_name and layer_name.startswith("CodeList_"):
                            codelist_refs.add(layer_name)

        except Exception as e:
            log(f"Error parsing style for ValueRelation refs: {e}", Qgis.Warning)

        return codelist_refs

    def _load_codelist_layer(self, wfs_url: str, layer_name: str, authcfg: str) -> None:
        """
        Load a CodeList WFS layer into the project.

        :param wfs_url: WFS server URL
        :param layer_name: CodeList layer name (e.g. 'CodeList_Artnamn_växter')
        :param authcfg: QGIS auth config ID
        """
        uri_parts = [
            f"url='{wfs_url}'",
            f"typename='{layer_name}'",
            "version='2.0.0'",
        ]
        if authcfg:
            uri_parts.append(f"authcfg='{authcfg}'")

        uri = " ".join(uri_parts)

        codelist_layer = QgsVectorLayer(uri, layer_name, "WFS")
        if codelist_layer.isValid():
            # Add as hidden layer (not shown in layer tree by default)
            QgsProject.instance().addMapLayer(codelist_layer, False)

            # Prefetch features in background so ValueRelation completer works
            # when user opens a feature form. Without this, the first form open is slow.
            task = _CodeListPrefetchTask(layer_name, codelist_layer)
            QgsApplication.taskManager().addTask(task)

            log(f"Auto-loading CodeList layer '{layer_name}' in background...", Qgis.Info)
        else:
            log(f"Failed to load CodeList layer '{layer_name}' from '{wfs_url}'.", Qgis.Warning)


class _CodeListPrefetchTask(QgsTask):
    """Background task that prefetches CodeList features into QGIS WFS cache."""

    def __init__(self, layer_name: str, layer: QgsVectorLayer):
        super().__init__(f"Laddar kodlista: {layer_name}")
        self._layer = layer
        self._layer_name = layer_name
        self._count = 0

    def run(self) -> bool:
        """Runs in background thread - iterates all features to populate WFS cache."""
        try:
            for _ in self._layer.getFeatures():
                self._count += 1
                if self.isCanceled():
                    return False
            return True
        except Exception:
            return False

    def finished(self, result: bool) -> None:
        """Called on main thread when task completes."""
        if result:
            log(f"CodeList '{self._layer_name}' loaded ({self._count} values).", Qgis.Info)
        else:
            log(f"CodeList '{self._layer_name}' prefetch failed or cancelled.", Qgis.Warning)
